spring:
  rabbitmq:
    host: localhost  # This is the service name for RabbitMQ in Docker Compose
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/db_chats
    username: postgres
    password: sandesh123
    hikari:
      connection-timeout: 20000  # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 20           # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 20      # maximum pool size
      idle-timeout: 10000        # maximum idle time for connection
      max-lifetime: 1000         # maximum lifetime in milliseconds of a connection in the pool after it is closed
      auto-commit: true          # default auto-commit behavior
      leak-detection-threshold: 200

  servlet:
    multipart:
      max-file-size: 35MB
      file-size-threshold: 35MB
      max-request-size: 35MB

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
